name: Reddit Mail Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install libraries
      run: |
        pip install feedparser
        pip install textblob
        pip install fpdf

    - name: Run Script
      run: python reddit_script.py
